FROM debian:stretch-slim
MAINTAINER Chris Done

################################################################################
# OS deps

RUN apt-get update && apt-get install -y \
       gnupg \
       gpgv && \
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80  --recv-keys BA3CBA3FFE22B574 \
      && echo 'deb     http://downloads.haskell.org/debian stretch main' >> /etc/apt/sources.list.d/haskell.list && \
   apt-get update && apt-get install -y \
    libtinfo5 \
    autoconf automake libtool make libgmp-dev ncurses-dev g++ python bzip2 ca-certificates \
    xz-utils \
    ghc-8.2.2 \
    alex \
    cabal-install-2.2 \
    happy \
    sudo xutils-dev \
    && apt-get install git -y \
    && apt-get clean

ENV LANG     C.UTF-8
ENV LC_ALL   C.UTF-8
ENV LANGUAGE C.UTF-8

################################################################################
# Getting the GHC sources and GHC as a bootstrap compiler

RUN cd; \
    mkdir ghc_build; \
    cd ghc_build; \
    git clone -b ghc-8.0 --recursive git://git.haskell.org/ghc.git ghc-8.0; \
    cd ghc-8.0; \
    git checkout ghc-8.0; \
    git submodule update --init

RUN apt-get install ghc -y

################################################################################
# Building GHC

RUN cd; \
    cd ghc_build/ghc-8.0; \
    cd mk; \
    sed -e 's/^#BuildFlavour = quickest$/BuildFlavour = quickest/' \
        build.mk.sample > build.mk; \
    cd ..; \
    ./boot

RUN cd; cd ghc_build/ghc-8.0 &&  ./configure

RUN cd; cd ghc_build/ghc-8.0 && make -j5

################################################################################
# Patching GHC

COPY ghc-8.0/Main.hs /root/ghc_build/ghc-8.0/ghc/Main.hs
COPY src/Prana/Types.hs /root/Types.hs
RUN tail -n +17 /root/Types.hs >> /root/ghc_build/ghc-8.0/ghc/Main.hs
RUN cd; cd ghc_build/ghc-8.0 && make inplace/bin/ghc-stage2 -j5 GhcStage1HcOpts="-package-id containers-0.5.7.1 -O0"
RUN mv /root/ghc_build/ghc-8.0/inplace/bin/ghc-stage2 /root/ghc_build/ghc-8.0/inplace/bin/ghc
ENV PATH="/root/ghc_build/ghc-8.0/inplace/bin:${PATH}"

################################################################################
# Setup an empty package database for prana

ENV PREFIX /root/prana

RUN mkdir $PREFIX && \
    touch $PREFIX/names.txt && \
    mkdir -p $PREFIX/package.conf.d && \
    ghc-pkg --package-db $PREFIX/package.conf.d recache && \
    ghc-pkg --package-db $PREFIX/package.conf.d list

################################################################################
# Building ghc-prim

WORKDIR /root/ghc_build/ghc-8.0/utils/genprimopcode
RUN echo 'import Distribution.Simple; main = defaultMain' > Setup.hs && \
    runhaskell Setup.hs configure && \
    runhaskell Setup.hs build
RUN cp dist/build/genprimopcode/genprimopcode .

WORKDIR /root/ghc_build/ghc-8.0/libraries/ghc-prim

# Clear the names database
RUN rm $PREFIX/names.txt; touch $PREFIX/names.txt

RUN cp /root/ghc_build/ghc-8.0/compiler/stage2/build/primops.txt ../../compiler/prelude/primops.txt && \
    ghc Setup.hs && \
    ./Setup configure --package-db $PREFIX/package.conf.d --prefix $PREFIX && \
    ./Setup build && \
    ./Setup install && \
    sed -i -e 's,^exposed-modules:,exposed-modules: GHC.Prim,' $PREFIX/package.conf.d/ghc-prim-*.conf && \
    ghc-pkg --package-db $PREFIX/package.conf.d recache

################################################################################
# Building integer-gmp

WORKDIR /root/ghc_build/ghc-8.0/libraries/integer-gmp
RUN ghc Setup.hs
RUN ./Setup configure --package-db $PREFIX/package.conf.d --prefix $PREFIX  --ghc-options=-O0 && \
    ./Setup build -v && \
    ./Setup install

################################################################################
# Building base

WORKDIR /root/ghc_build/ghc-8.0/libraries/base/
RUN echo 'import Distribution.Simple; main = defaultMainWithHooks autoconfUserHooks' > Setup.hs
RUN ghc -hide-all-packages -package Cabal Setup.hs -XNoImplicitPrelude
RUN ./Setup configure -finteger-gmp --package-db $PREFIX/package.conf.d --prefix $PREFIX --ghc-options=-O0 && \
    ./Setup build -v && \
    ./Setup install
